Repository Cafe-MOAS/CafeMOA_Backend, pull requests merged in 2024-01, with the labels that each got.

#2 feat: Add a Cafe Entity
  .idea/vcs.xml
  .idea/workspace.xml
  CafeMoa/src/main/java/CafeMoa/domain/Cafe.java
Labels: Feat, 김인서

#4 feat: Category 엔티티 추가, Service, Repository, Controller 생성
  CafeMoa/src/main/java/CafeMoa/controller/CafeController.java
  CafeMoa/src/main/java/CafeMoa/controller/MemberController.java
  CafeMoa/src/main/java/CafeMoa/controller/ReviewController.java
  CafeMoa/src/main/java/CafeMoa/domain/Category.java
  CafeMoa/src/main/java/CafeMoa/domain/category/CafeCategory.java
  CafeMoa/src/main/java/CafeMoa/domain/category/Category.java
  CafeMoa/src/main/java/CafeMoa/domain/category/ReviewCategory.java
  CafeMoa/src/main/java/CafeMoa/repository/CafeRepository.java
  CafeMoa/src/main/java/CafeMoa/repository/CategoryRepository.java
  CafeMoa/src/main/java/CafeMoa/repository/MemberRepository.java
  CafeMoa/src/main/java/CafeMoa/repository/ReviewRepository.java
  CafeMoa/src/main/java/CafeMoa/service/CafeService.java
  CafeMoa/src/main/java/CafeMoa/service/MemberService.java
  CafeMoa/src/main/java/CafeMoa/service/ReviewService.java
Labels: Feat, 정찬민

#5 feat: review entity 추가
  .idea/workspace.xml
  CafeMoa/src/main/java/CafeMoa/domain/Review.java
Labels: Feat, 오영록

#8 feat: 데이터베이스 설정 추가
  CafeMoa/build.gradle
  CafeMoa/src/main/java/CafeMoa/domain/Cafe.java
  CafeMoa/src/main/java/CafeMoa/domain/Review.java
  CafeMoa/src/main/resources/application.yml
Labels: Feat, 박상욱
